"use node";

import { v } from "convex/values";
import { action } from "./_generated/server";
import {addDatabaseToPageType, addPageToDatabaseType} from '../types/Types'

const { Client } = require('@notionhq/client');



export const addDatabaseToPage = action(

     async(ctx, args:addDatabaseToPageType) => {
        const notion = new Client({ auth:args.notionKey});
        const pageId = args.notionUrl;
        const response = await notion.databases.create({
            parent: {
              type: "page_id",
              page_id: pageId,
            },
            // cover: {
            //   type: "external",
            //   external: {
            //     url: "",
            //   },
            // },
            title: [
              {
                type: "text",
                text: {
                  content: args.topic,
                  link: null,
                },
              },
            ],
            properties: {
              Name: {
                title: {},
              },
              Description: {
                rich_text: {},
              },              
            },
          });
        console.log(response);
    },
  );


  export const addPageToDatabase = action(
    async(ctx, args:addPageToDatabaseType) => {
        const notion = new Client({ auth:args.notionKey });
        const parentDatabaseId = args.notionUrl;
        const response = await notion.pages.create({
            // "cover": {
            //     "type": "external",
            //     "external": {
            //         "url": "https://upload.wikimedia.org/wikipedia/commons/6/62/Tuscankale.jpg"
            //     }
            // },
            "icon": {
                "type": "emoji",
                "emoji": "✏️"
            },
            "parent": {
                "type": "database_id",
                "database_id": parentDatabaseId,
            },
            "properties": {
                "Name": {
                    "title": [
                        {
                            "text": {
                                "content": args.topic
                            }
                        }
                    ]
                },
            },

            //content generated by chatGpt
            "children": [
                {
                    "object": "block",
                    "heading_2": {
                        "rich_text": [
                            {
                                "text": {
                                    "content": `Here's some important information about ${args.topic}`
                                }
                            }
                        ]
                    }
                },
                
                
                {
                  "object": "block",
                  "paragraph": {
                      "rich_text": [
                          {
                              "text": {
                                  "content": args.content,
                              },
                              
                          }
                      ],
                      "color": "default"
                  }
              },

              // summary generated by youtube and chatGpt

              {
                "object": "block",
                "heading_2": {
                    "rich_text": [
                        {
                            "text": {
                                "content": `https://www.youtube.com/watch?v=${args.videoId}` 
                            }
                        }
                    ]
                }
            },

            {
                "object": "block",
                "heading_2": {
                    "rich_text": [
                        {
                            "text": {
                                "content": "here's a summary of the above video ."
                            }
                        }
                    ]
                }
            },

                {
                    "object": "block",
                    "paragraph": {
                        "rich_text": [
                            {
                                "text": {
                                    "content": args.trancriptSummary,
                                    "link": {
                                        "url": `https://www.youtube.com/watch?v=${args.videoId}` 
                                    }
                                },
                                "href": `https://www.youtube.com/watch?v=${args.videoId}` 
                            }
                        ],
                        "color": "default"
                    }
                },
      
            ]
        });
          console.log(response);
        
      
    },
  );


  export const updatePage = action(
    async(ctx, args:addPageToDatabaseType) => {
        const notion = new Client({ auth:args.notionKey });
        const parentDatabaseId = args.notionUrl;
        const pageId = 'd9b08ec6f4b646cca2a0622b48caa86a';
        const response = await notion.pages.update({
          page_id: pageId,
          "properties": {
            "Name": {
                "title": [
                    {
                        "text": {
                            "content": "Updated Page Name"
                        }
                    }
                ]
            },
          },
        });
        console.log(response);
      })