/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.3.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as helpSection from "../helpSection";
import type * as http from "../http";
import type * as httpActions from "../httpActions";
import type * as notionAction from "../notionAction";
import type * as openAi from "../openAi";
import type * as openaiAction from "../openaiAction";
import type * as testFunctions from "../testFunctions";
import type * as youtubeAction from "../youtubeAction";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  helpSection: typeof helpSection;
  http: typeof http;
  httpActions: typeof httpActions;
  notionAction: typeof notionAction;
  openAi: typeof openAi;
  openaiAction: typeof openaiAction;
  testFunctions: typeof testFunctions;
  youtubeAction: typeof youtubeAction;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
