// import { useAction } from "convex/react";
// import { NextRequest, NextResponse } from "next/server";
// import { json } from "stream/consumers";
// import { api } from "../../../../convex/_generated/api";
// import { addPageToDatabaseType } from "../../../../types/Types";
// const { Client } = require('@notionhq/client');

// export async function GET(){
//     return NextResponse.json({hello:"world"})
// }



// /* example request 

// {
// "archived": "False",
// "cover": "",
// "created_by": {
// "id": "9367ff33-d2b0-4675-8551-5b4d805e1b29",
// "object": "user"
// },
// "created_time": "2023-10-04T14:48:00.000Z",
// "icon": "",
// "id": "ac2913a4-45db-44ba-8ab4-63e51f9099e5",
// "last_edited_by": {
// "id": "9367ff33-d2b0-4675-8551-5b4d805e1b29",
// "object": "user"
// },
// "last_edited_time": "2023-10-04T14:48:00.000Z",
// "object": "page",
// "parent": {
// "database_id": "dc8c96a6-3a14-4a17-972d-50e0ef7ced88",
// "type": "database_id"
// },
// "properties": {
// "Name": "test2"
// },
// "public_url": "",
// "title": "test2",
// "url": "https://www.notion.so/test2-ac2913a445db44ba8ab463e51f9099e5"
// }


// */
// export async function POST(req:NextRequest){
//     let reqSuccessful = true;
//     const body = await req.json()
//     console.log(body)
//     const notion = new Client({ auth:"secret_sKLbBIfkZwp8K9DjfsyOZ6PGybPsPYUYVTbKmcvHet2" });

//     async function getPageData(){ // retrieve title of the page from url
//         var retrievedPage = await notion.pages.retrieve({ page_id: '14596e03169740548159caa0658ca4a8' });
//         console.log(retrievedPage.properties.Name.title[0].plain_text);
//     }

//     //generate content for the updatedPage;


//     try{
//         getPageData();
    
//         // updatePage({
//         //     notionUrl,
//         //     content: "gptData",
//         //     topic: "values.topic",
//         //     trancriptSummary: "youtubeData.summary",
//         //     videoId: "youtubeData.videoId",
//         //     notionKey: "secret_sKLbBIfkZwp8K9DjfsyOZ6PGybPsPYUYVTbKmcvHet2"
//         //   })

//     }catch{
//         reqSuccessful=false
//     }
 

//      async function updatePage ( args:addPageToDatabaseType) {

//             const notion = new Client({ auth:args.notionKey });
//             const parentDatabaseId = args.notionUrl;
//             const pageId = '14596e03169740548159caa0658ca4a8';
//             const response = await notion.blocks.children.append({
//                 block_id: pageId,
//                 "children": [
//                     {
//                         "object": "block",
//                         "heading_2": {
//                             "rich_text": [
//                                 {
//                                     "text": {
//                                         "content": `Here's some important information about ${args.topic}`
//                                     }
//                                 }
//                             ]
//                         }
//                     },
                    
                    
//                     {
//                       "object": "block",
//                       "paragraph": {
//                           "rich_text": [
//                               {
//                                   "text": {
//                                       "content": args.content,
//                                   },
                                  
//                               }
//                           ],
//                           "color": "default"
//                       }
//                   },
    
//                   // summary generated by youtube and chatGpt
    
//                   {
//                     "object": "block",
//                     "heading_2": {
//                         "rich_text": [
//                             {
//                                 "text": {
//                                     "content": `https://www.youtube.com/watch?v=${args.videoId}` 
//                                 }
//                             }
//                         ]
//                     }
//                 },
    
//                 {
//                     "object": "block",
//                     "heading_2": {
//                         "rich_text": [
//                             {
//                                 "text": {
//                                     "content": "here's a summary of the above video ."
//                                 }
//                             }
//                         ]
//                     }
//                 },
    
//                     {
//                         "object": "block",
//                         "paragraph": {
//                             "rich_text": [
//                                 {
//                                     "text": {
//                                         "content": args.trancriptSummary,
//                                         "link": {
//                                             "url": `https://www.youtube.com/watch?v=${args.videoId}` 
//                                         }
//                                     },
//                                     "href": `https://www.youtube.com/watch?v=${args.videoId}` 
//                                 }
//                             ],
//                             "color": "default"
//                         }
//                     },
          
//                 ]
//               });
//             console.log(response);
//           }



//     return NextResponse.json({requestCompleted:reqSuccessful})
// }